apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-grey
  namespace: applications
  name: nginx-grey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-grey
  template:
    metadata:
      labels:
        app: nginx-grey
    spec:
      containers:
      - image: nginx:latest
        name: nginx
