apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-green
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  namespace: applications
  name: nginx-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-green
  template:
    metadata:
      labels:
        app: nginx-green
    spec:
      containers:
      - image: nginx:latest
        name: nginx