apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-19"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    cluster: in-cluster
    cluster-scope: root
  name: app-nginx-grey
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: applications
  source:
    path: applications/nginx-grey
    repoURL: https://github.com:thusharajayakody1/gitops-test.git
    targetRevision: 849d374
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
